### ISSUE TITLE
#bug The wav files seem all broken. 

### ISSUE THREAD

**Issue by shincling** [microsoft/DNS-Challenge#1]
I used the code to noisyspeech_synthesizer_singleprocess.py to synthesize the data.
But there is a problem 

Traceback (most recent call last):
  File "noisyspeech_synthesizer_singleprocess.py", line 361, in <module>
    main_body()
  File "noisyspeech_synthesizer_singleprocess.py", line 333, in main_body
    noise_source_files, noise_clipped_files, noise_low_activity_files = main_gen(params)
  File "noisyspeech_synthesizer_singleprocess.py", line 164, in main_gen
    gen_audio(True, params, clean_index)
  File "noisyspeech_synthesizer_singleprocess.py", line 119, in gen_audio
    build_audio(is_clean, params, index, audio_samples_length)
  File "noisyspeech_synthesizer_singleprocess.py", line 69, in build_audio
    input_audio, fs_input = audioread(source_files[idx])
  File "/mnt/lustre/xushuang4/shijing/codes/DNS-Challenge-master/audiolib.py", line 42, in audioread
    audio, sample_rate = sf.read(path, start=start, stop=stop)
  File "/mnt/lustre/xushuang4/anaconda2/envs/conda_shin_pyannote/lib/python3.6/site-packages/soundfile.py", line 373, in read
    subtype, endian, format, closefd) as f:
  File "/mnt/lustre/xushuang4/anaconda2/envs/conda_shin_pyannote/lib/python3.6/site-packages/soundfile.py", line 740, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/mnt/lustre/xushuang4/anaconda2/envs/conda_shin_pyannote/lib/python3.6/site-packages/soundfile.py", line 1265, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/mnt/lustre/xushuang4/anaconda2/envs/conda_shin_pyannote/lib/python3.6/site-packages/soundfile.py", line 1455, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening './datasets/clean/book_11069_chp_0022_reader_08200_33.wav': File contains data in an unknown format.

I thought it was the problem of my soundfile or librosa at first. But I tried in several different versions that all got the same problem. Then I found I could use it to read other .wav files.

Then I try to open the files directly under player in Win10 system, it says the files may be broken. 
Please check it. Cause I think it's a very serious problem.

**Comment by chandanka90** [comment]
@shincling Please clone the repo. Just downloading the datasets has this format issue. It should work fine if you clone the entire repository.

**Comment by shincling** [comment]
Thanks. Solved.  It really takes a long time to download the lfs documents. 
BTW,  there seems a short of "import random" in  noisyspeech_synthesizer_singleprocess.py.

**Comment by chandanka90** [comment]
Solved
