### ISSUE TITLE
no response error for WAcc.py 

### ISSUE THREAD

**Issue by heisenberg-kim** [microsoft/DNS-Challenge#155]
when i tried to run WAcc.py script, i got a error message below. 

Error occured during scoring
response is  <Response [500]>
Traceback (most recent call last):
  File "WAcc.py", line 54, in <module>
    main(args)
  File "WAcc.py", line 38, in main
    score_dict = {'file_name': os.path.basename(fpath), 'wacc': wacc}
UnboundLocalError: local variable 'wacc' referenced before assignment

Could you give me some advices or let me know what happen??

**Comment by zly19** [comment]
hello，I encountered the same problem, did you solve it?
