### ISSUE TITLE
error on running noisyspeech_synthesizer_singleprocess.py

### ISSUE THREAD

**Issue by dttlgotv** [microsoft/DNS-Challenge#35]
python noisyspeech_synthesizer_singleprocess.py
Number of files to be synthesized: 60000
WARNING: Audio type not supported
Traceback (most recent call last):
  File "noisyspeech_synthesizer_singleprocess.py", line 537, in <module>
    main_body()
  File "noisyspeech_synthesizer_singleprocess.py", line 508, in main_body
    noise_source_files, noise_clipped_files, noise_low_activity_files = main_gen(params)
  File "noisyspeech_synthesizer_singleprocess.py", line 168, in main_gen
    gen_audio(True, params, clean_index)
  File "noisyspeech_synthesizer_singleprocess.py", line 132, in gen_audio
    build_audio(is_clean, params, index, audio_samples_length)
  File "noisyspeech_synthesizer_singleprocess.py", line 82, in build_audio
    input_audio, fs_input = audioread(source_files[idx])
  File "/data1/dtln/DNS-Challenge/audiolib.py", line 45, in audioread
    if len(audio.shape) == 1:  # mono
UnboundLocalError: local variable 'audio' referenced before assignment

**Comment by e349808405** [comment]
Have you solved the problem

**Comment by dttlgotv** [comment]
yes，data problem

发自我的iPhone


------------------ Original ------------------

**Comment by jsjur** [comment]
@dttlgotv I am running into the same problem, what did you do to fix the error?

**Comment by dttlgotv** [comment]
> 
> 
> @dttlgotv I am running into the same problem, what did you do to fix the error?

You must get the data using lfs.
