### ISSUE TITLE
dataset wavefile format - WARNING: Audio type not supported

### ISSUE THREAD

**Issue by raikarsagar** [microsoft/DNS-Challenge#9]
Number of files to be synthesized: 60000
WARNING: Audio type not supported
Traceback (most recent call last):
  File "noisyspeech_synthesizer_singleprocess.py", line 351, in <module>
    main_body()
  File "noisyspeech_synthesizer_singleprocess.py", line 323, in main_body
    noise_source_files, noise_clipped_files, noise_low_activity_files = main_gen(params)
  File "noisyspeech_synthesizer_singleprocess.py", line 155, in main_gen
    gen_audio(True, params, clean_index)
  File "noisyspeech_synthesizer_singleprocess.py", line 119, in gen_audio
    build_audio(is_clean, params, index, audio_samples_length)
  File "noisyspeech_synthesizer_singleprocess.py", line 69, in build_audio
    input_audio, fs_input = audioread(source_files[idx])
  File "/home/stuart/sagar/DNS-Challenge/audiolib.py", line 45, in audioread
    if len(audio.shape) == 1:  # mono
UnboundLocalError: local variable 'audio' referenced before assignment

the wav files are in audio x-wav format. Seems they dont have header. Do we have to reformat this or downloading failure?

Any support is appreciated
Thanks in advance

**Comment by jsjur** [comment]
Hey @raikarsagar did you resolve this somehow?

**Comment by raikarsagar** [comment]
issue was resolved after downloading the audio files properly, git lfs has to be used
